# Core
brew 'git'
brew 'vim'
brew 'zsh'

# Programming
brew 'node'
brew 'nvm'
brew 'go'
brew 'rbenv'
brew 'python'
brew 'pipx'

# Utilities
brew 'mobile-shell'
brew 'httpie'
brew 'jq'
brew 'neofetch'
brew 'eza'
brew 'font-hack-nerd-font'
brew 'starship'

# Kubernetes
brew 'kubectl'
brew 'helm'
brew 'minikube'
brew 'k9s'

# Applications
cask 'iterm2'
cask 'warp'
cask 'obsidian'
cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'alfred'
cask 'bartender'
cask 'docker'
cask 'todoist'
cask 'spotify'
