source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/completion.zsh
# source ~/.zsh/prompt.zsh
source ~/.zsh/starship.zsh

eval "$(starship init zsh)"
